### ISSUE TITLE
I would like to post "album title" ( not "song title" )

### ISSUE THREAD

**Issue by dragon3** [dragon3/rhythmbox-twitter-plugin#3]
I would like to improve plugin's configuration dialog, and add this setting.

**Comment by leomeloxp** [comment]
Can you put it a bit more clear? I haven't got the album title instead of song title. I think it's pretty easy to set that up, but I need an example of what you want. Post how would you want the twitt to show, and then we edit it so you can have your custom twitt format. I did that for me, it's pretty simple.

**Comment by leomeloxp** [comment]
Oh, nevermind. I noticed that it was solved already ^^' Sorry, my mistake.

**Comment by dragon3** [comment]
I usually listen to album, not one song.
For example, 
I usually listen to all songs of "Abby Road".
I don't listen to "Come Together" only.

I would like to post something like

> nowlistening to "Abby Road" by Beatles.

So, I would like to add this setting like below,

<pre>
When you post?
 o When playing song changed, post song title.
 o When playing song album changed, post album title.
 o When you push the "Post" button.
</pre>

**Comment by dragon3** [comment]
Done! : dc615656590ff0254cfb8c454d4879c1a131d2c3
